import { generateTypeScript } from '../src/cli/generators/typescript';
import { generateJsonSchema } from '../src/cli/generators/json-schema';
import { RegistrySnapshot } from '../src/services/registry/registry.types';

function createSnapshot(overrides?: Partial<RegistrySnapshot>): RegistrySnapshot {
  return {
    generatedAt: Date.now(),
    keyPrefix: 'test',
    entities: [],
    ...overrides,
  };
}

describe('CLI Generators', () => {
  describe('TypeScript generator', () => {
    it('should produce valid namespace output', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              WithdrawCommand: {
                kind: 'command',
                schema: {
                  type: 'object',
                  required: ['accountId', 'amount'],
                  properties: {
                    accountId: { type: 'string' },
                    amount: { type: 'number' },
                  },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);

      expect(output).toContain('export namespace AccountEntity');
      expect(output).toContain('export interface WithdrawCommand');
      expect(output).toContain('accountId: string;');
      expect(output).toContain('amount: number;');
      expect(output).toContain('/** command — service: bank-svc */');
      expect(output).toContain('Auto-generated by atomic-queues CLI');
    });

    it('should handle entities with no schemas (name-only)', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              PlaceOrderCommand: { kind: 'command' },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain('export namespace OrderEntity');
      expect(output).toContain('export interface PlaceOrderCommand');
      expect(output).not.toContain('undefined');
    });

    it('should generate reply interfaces for queries', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              GetBalanceQuery: {
                kind: 'query',
                schema: {
                  type: 'object',
                  required: ['accountId'],
                  properties: { accountId: { type: 'string' } },
                },
                replySchema: {
                  type: 'object',
                  required: ['balance'],
                  properties: { balance: { type: 'number' } },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain('export interface GetBalanceQuery');
      expect(output).toContain('export interface GetBalanceQueryReply');
      expect(output).toContain('balance: number;');
    });

    it('should handle multiple entity types', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: { Deposit: { kind: 'command' } },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
          {
            entityType: 'game-table',
            serviceName: 'casino-svc',
            version: '1.0.0',
            messages: { MakeBet: { kind: 'command' } },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain('export namespace AccountEntity');
      expect(output).toContain('export namespace GameTableEntity');
    });

    it('should handle array and enum types', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              CreateOrder: {
                kind: 'command',
                schema: {
                  type: 'object',
                  properties: {
                    items: { type: 'array', items: { type: 'string' } },
                    status: { type: 'string', enum: ['pending', 'shipped'] },
                    active: { type: 'boolean' },
                  },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain("'pending' | 'shipped'");
      expect(output).toContain('string[]');
      expect(output).toContain('boolean');
    });
  });

  describe('JSON Schema generator', () => {
    it('should produce valid JSON Schema structure', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              WithdrawCommand: {
                kind: 'command',
                schema: {
                  type: 'object',
                  required: ['amount'],
                  properties: { amount: { type: 'number' } },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateJsonSchema(snapshot);
      expect(output.$schema).toBe('http://json-schema.org/draft-07/schema#');
      expect(output.title).toBe('atomic-queues Registry Schema');
      expect(output.definitions['account.WithdrawCommand']).toBeDefined();
      expect(output.definitions['account.WithdrawCommand'].title).toBe('WithdrawCommand');
      expect(output.definitions['account.WithdrawCommand'].required).toEqual(['amount']);
    });

    it('should include reply schemas for queries', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              GetBalance: {
                kind: 'query',
                schema: { type: 'object' },
                replySchema: {
                  type: 'object',
                  properties: { balance: { type: 'number' } },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateJsonSchema(snapshot);
      expect(output.definitions['account.GetBalanceReply']).toBeDefined();
      expect(output.definitions['account.GetBalanceReply'].title).toBe('GetBalanceReply');
    });

    it('should handle entities without schemas', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              PlaceOrder: { kind: 'command' },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateJsonSchema(snapshot);
      expect(output.definitions['order.PlaceOrder'].type).toBe('object');
    });
  });
});
