import { generateTypeScript } from '../src/cli/generators/typescript';
import { generateJsonSchema } from '../src/cli/generators/json-schema';
import { generateClasses } from '../src/cli/generators/classes';
import { RegistrySnapshot } from '../src/services/registry/registry.types';

function createSnapshot(overrides?: Partial<RegistrySnapshot>): RegistrySnapshot {
  return {
    generatedAt: Date.now(),
    keyPrefix: 'test',
    entities: [],
    ...overrides,
  };
}

describe('CLI Generators', () => {
  describe('TypeScript generator', () => {
    it('should produce valid namespace output', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              WithdrawCommand: {
                kind: 'command',
                schema: {
                  type: 'object',
                  required: ['accountId', 'amount'],
                  properties: {
                    accountId: { type: 'string' },
                    amount: { type: 'number' },
                  },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);

      expect(output).toContain('export namespace AccountEntity');
      expect(output).toContain('export interface WithdrawCommand');
      expect(output).toContain('accountId: string;');
      expect(output).toContain('amount: number;');
      expect(output).toContain('/** command — service: bank-svc */');
      expect(output).toContain('Auto-generated by atomic-queues CLI');
    });

    it('should handle entities with no schemas (name-only)', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              PlaceOrderCommand: { kind: 'command' },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain('export namespace OrderEntity');
      expect(output).toContain('export interface PlaceOrderCommand');
      expect(output).not.toContain('undefined');
    });

    it('should generate reply interfaces for queries', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              GetBalanceQuery: {
                kind: 'query',
                schema: {
                  type: 'object',
                  required: ['accountId'],
                  properties: { accountId: { type: 'string' } },
                },
                replySchema: {
                  type: 'object',
                  required: ['balance'],
                  properties: { balance: { type: 'number' } },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain('export interface GetBalanceQuery');
      expect(output).toContain('export interface GetBalanceQueryReply');
      expect(output).toContain('balance: number;');
    });

    it('should handle multiple entity types', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: { Deposit: { kind: 'command' } },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
          {
            entityType: 'game-table',
            serviceName: 'casino-svc',
            version: '1.0.0',
            messages: { MakeBet: { kind: 'command' } },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain('export namespace AccountEntity');
      expect(output).toContain('export namespace GameTableEntity');
    });

    it('should handle array and enum types', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              CreateOrder: {
                kind: 'command',
                schema: {
                  type: 'object',
                  properties: {
                    items: { type: 'array', items: { type: 'string' } },
                    status: { type: 'string', enum: ['pending', 'shipped'] },
                    active: { type: 'boolean' },
                  },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateTypeScript(snapshot);
      expect(output).toContain("'pending' | 'shipped'");
      expect(output).toContain('string[]');
      expect(output).toContain('boolean');
    });
  });

  describe('JSON Schema generator', () => {
    it('should produce valid JSON Schema structure', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              WithdrawCommand: {
                kind: 'command',
                schema: {
                  type: 'object',
                  required: ['amount'],
                  properties: { amount: { type: 'number' } },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateJsonSchema(snapshot);
      expect(output.$schema).toBe('http://json-schema.org/draft-07/schema#');
      expect(output.title).toBe('atomic-queues Registry Schema');
      expect(output.definitions['account.WithdrawCommand']).toBeDefined();
      expect(output.definitions['account.WithdrawCommand'].title).toBe('WithdrawCommand');
      expect(output.definitions['account.WithdrawCommand'].required).toEqual(['amount']);
    });

    it('should include reply schemas for queries', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'account',
            serviceName: 'bank-svc',
            version: '1.0.0',
            messages: {
              GetBalance: {
                kind: 'query',
                schema: { type: 'object' },
                replySchema: {
                  type: 'object',
                  properties: { balance: { type: 'number' } },
                },
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateJsonSchema(snapshot);
      expect(output.definitions['account.GetBalanceReply']).toBeDefined();
      expect(output.definitions['account.GetBalanceReply'].title).toBe('GetBalanceReply');
    });

    it('should handle entities without schemas', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              PlaceOrder: { kind: 'command' },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const output = generateJsonSchema(snapshot);
      expect(output.definitions['order.PlaceOrder'].type).toBe('object');
    });
  });

  describe('Classes generator', () => {
    it('should produce decorated class files per entity type', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'warehouse',
            serviceName: 'warehouse-svc',
            version: '1.0.0',
            messages: {
              ReserveStockCommand: {
                kind: 'command',
                schema: {
                  type: 'object',
                  required: ['sku', 'quantity'],
                  properties: {
                    sku: { type: 'string' },
                    quantity: { type: 'integer' },
                  },
                },
                entityIdField: 'sku',
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const files = generateClasses(snapshot);
      expect(files).toHaveLength(2); // warehouse.ts + index.ts

      const warehouseFile = files.find(f => f.filename === 'warehouse.ts')!;
      expect(warehouseFile).toBeDefined();
      expect(warehouseFile.content).toContain("@EntityType('warehouse')");
      expect(warehouseFile.content).toContain('export class ReserveStockCommand');
      expect(warehouseFile.content).toContain('@QueueEntityId() readonly sku!: string;');
      expect(warehouseFile.content).toContain('readonly quantity!: number;');
      expect(warehouseFile.content).toContain('export interface ReserveStockCommandData');
      expect(warehouseFile.content).toContain('constructor(data: ReserveStockCommandData)');
      expect(warehouseFile.content).toContain("import { EntityType, QueueEntityId } from 'atomic-queues';");

      const indexFile = files.find(f => f.filename === 'index.ts')!;
      expect(indexFile).toBeDefined();
      expect(indexFile.content).toContain("export * from './warehouse';");
    });

    it('should generate Reply-branded queries with reply interfaces', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'warehouse',
            serviceName: 'warehouse-svc',
            version: '1.0.0',
            messages: {
              GetStockQuery: {
                kind: 'query',
                schema: {
                  type: 'object',
                  required: ['sku'],
                  properties: { sku: { type: 'string' } },
                },
                replySchema: {
                  type: 'object',
                  required: ['sku', 'available'],
                  properties: {
                    sku: { type: 'string' },
                    available: { type: 'integer' },
                  },
                },
                entityIdField: 'sku',
              },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const files = generateClasses(snapshot);
      const warehouseFile = files.find(f => f.filename === 'warehouse.ts')!;

      expect(warehouseFile.content).toContain('export interface GetStockQueryReply');
      expect(warehouseFile.content).toContain('available: number;');
      expect(warehouseFile.content).toContain('implements Reply<GetStockQueryReply>');
      expect(warehouseFile.content).toContain('declare readonly __reply: GetStockQueryReply;');
      expect(warehouseFile.content).toContain("import type { Reply } from 'atomic-queues';");
    });

    it('should handle entities with no schemas', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'order',
            serviceName: 'shop-svc',
            version: '1.0.0',
            messages: {
              PlaceOrder: { kind: 'command' },
            },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const files = generateClasses(snapshot);
      const orderFile = files.find(f => f.filename === 'order.ts')!;
      expect(orderFile).toBeDefined();
      expect(orderFile.content).toContain('export class PlaceOrder');
      expect(orderFile.content).toContain('export interface PlaceOrderData');
    });

    it('should generate multiple entity files and barrel index', () => {
      const snapshot = createSnapshot({
        entities: [
          {
            entityType: 'warehouse',
            serviceName: 'warehouse-svc',
            version: '1.0.0',
            messages: { Reserve: { kind: 'command' } },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
          {
            entityType: 'billing',
            serviceName: 'billing-svc',
            version: '1.0.0',
            messages: { Charge: { kind: 'command' } },
            registeredAt: Date.now(),
            lastHeartbeat: Date.now(),
          },
        ],
      });

      const files = generateClasses(snapshot);
      expect(files).toHaveLength(3); // warehouse.ts, billing.ts, index.ts

      const index = files.find(f => f.filename === 'index.ts')!;
      expect(index.content).toContain("export * from './warehouse';");
      expect(index.content).toContain("export * from './billing';");
    });
  });
});
