import { RegistrySnapshot } from '../../domain/interfaces/registry.types';

export function generateTypeScript(snapshot: RegistrySnapshot): string {
  const lines: string[] = [];

  lines.push('// Auto-generated by atomic-queues CLI');
  lines.push(`// Source: Redis registry (prefix: '${snapshot.keyPrefix}')`);
  lines.push(`// Generated: ${new Date(snapshot.generatedAt).toISOString()}`);
  lines.push('// DO NOT EDIT — regenerate with: npx atomic-queues generate --ts');
  lines.push('');

  // ── Per-entity namespaces with message interfaces ──────────────────────

  for (const entity of snapshot.entities) {
    const namespace = pascalCase(entity.entityType) + 'Entity';
    lines.push(`export namespace ${namespace} {`);

    for (const [msgName, spec] of Object.entries(entity.messages)) {
      lines.push(`  /** ${spec.kind} — service: ${entity.serviceName} */`);
      lines.push(`  export interface ${msgName} {`);

      if (spec.schema?.properties) {
        for (const [prop, propSchema] of Object.entries(spec.schema.properties)) {
          const tsType = jsonSchemaTypeToTS(propSchema as any);
          const required = spec.schema.required?.includes(prop) ?? false;
          lines.push(`    ${prop}${required ? '' : '?'}: ${tsType};`);
        }
      }

      lines.push('  }');
      lines.push('');

      if (spec.kind === 'query' && spec.replySchema?.properties) {
        lines.push(`  export interface ${msgName}Reply {`);
        for (const [prop, propSchema] of Object.entries(spec.replySchema.properties)) {
          const tsType = jsonSchemaTypeToTS(propSchema as any);
          const required = spec.replySchema.required?.includes(prop) ?? false;
          lines.push(`    ${prop}${required ? '' : '?'}: ${tsType};`);
        }
        lines.push('  }');
        lines.push('');
      }
    }

    lines.push('}');
    lines.push('');
  }

  // ── DispatchMap — maps entity type → message name → payload type ───────

  lines.push('// ── Dispatch type maps (for use with TypedDispatch / TypedDispatchAndWait) ──');
  lines.push('');
  lines.push('export interface DispatchMap {');

  for (const entity of snapshot.entities) {
    const namespace = pascalCase(entity.entityType) + 'Entity';
    lines.push(`  '${entity.entityType}': {`);

    for (const [msgName, spec] of Object.entries(entity.messages)) {
      const hasSchema = spec.schema?.properties && Object.keys(spec.schema.properties).length > 0;
      const type = hasSchema ? `${namespace}.${msgName}` : 'Record<string, any>';
      lines.push(`    '${msgName}': ${type};`);
    }

    lines.push('  };');
  }

  lines.push('}');
  lines.push('');

  // ── ReplyMap — maps entity type → query name → reply type ─────────────

  const hasAnyReply = snapshot.entities.some((e) =>
    Object.values(e.messages).some((m) => m.kind === 'query' && m.replySchema?.properties),
  );

  if (hasAnyReply) {
    lines.push('export interface ReplyMap {');

    for (const entity of snapshot.entities) {
      const namespace = pascalCase(entity.entityType) + 'Entity';
      const queries = Object.entries(entity.messages).filter(
        ([, spec]) => spec.kind === 'query' && spec.replySchema?.properties,
      );

      if (queries.length > 0) {
        lines.push(`  '${entity.entityType}': {`);
        for (const [msgName] of queries) {
          lines.push(`    '${msgName}': ${namespace}.${msgName}Reply;`);
        }
        lines.push('  };');
      }
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function jsonSchemaTypeToTS(schema: { type?: string; items?: any; enum?: any[] }): string {
  if (!schema.type) return 'any';
  switch (schema.type) {
    case 'string':
      return schema.enum ? schema.enum.map((v: any) => `'${v}'`).join(' | ') : 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return schema.items ? `${jsonSchemaTypeToTS(schema.items)}[]` : 'any[]';
    case 'object':
      return 'Record<string, any>';
    case 'null':
      return 'null';
    default:
      return 'any';
  }
}

function pascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}
