import { RegistrySnapshot } from '../../services/registry/registry.types';

export function generateTypeScript(snapshot: RegistrySnapshot): string {
  const lines: string[] = [];

  lines.push('// Auto-generated by atomic-queues CLI');
  lines.push(`// Source: Redis registry (prefix: '${snapshot.keyPrefix}')`);
  lines.push(`// Generated: ${new Date(snapshot.generatedAt).toISOString()}`);
  lines.push('// DO NOT EDIT — regenerate with: npx atomic-queues generate --ts');
  lines.push('');

  for (const entity of snapshot.entities) {
    const namespace = pascalCase(entity.entityType) + 'Entity';
    lines.push(`export namespace ${namespace} {`);

    for (const [msgName, spec] of Object.entries(entity.messages)) {
      lines.push(`  /** ${spec.kind} — service: ${entity.serviceName} */`);
      lines.push(`  export interface ${msgName} {`);

      if (spec.schema?.properties) {
        for (const [prop, propSchema] of Object.entries(spec.schema.properties)) {
          const tsType = jsonSchemaTypeToTS(propSchema as any);
          const required = spec.schema.required?.includes(prop) ?? false;
          lines.push(`    ${prop}${required ? '' : '?'}: ${tsType};`);
        }
      }

      lines.push('  }');
      lines.push('');

      if (spec.kind === 'query' && spec.replySchema?.properties) {
        lines.push(`  export interface ${msgName}Reply {`);
        for (const [prop, propSchema] of Object.entries(spec.replySchema.properties)) {
          const tsType = jsonSchemaTypeToTS(propSchema as any);
          const required = spec.replySchema.required?.includes(prop) ?? false;
          lines.push(`    ${prop}${required ? '' : '?'}: ${tsType};`);
        }
        lines.push('  }');
        lines.push('');
      }
    }

    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function jsonSchemaTypeToTS(schema: { type?: string; items?: any; enum?: any[] }): string {
  if (!schema.type) return 'any';
  switch (schema.type) {
    case 'string': return schema.enum ? schema.enum.map((v: any) => `'${v}'`).join(' | ') : 'string';
    case 'number':
    case 'integer': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return schema.items ? `${jsonSchemaTypeToTS(schema.items)}[]` : 'any[]';
    case 'object': return 'Record<string, any>';
    case 'null': return 'null';
    default: return 'any';
  }
}

function pascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}
